name: mws
description: A Web3 Multi Wallet Sender Flutter Web App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  web3dart: ^2.7.3
  file_picker: ^10.2.0
  url_launcher: ^6.2.5
  http: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  url_strategy: ^0.3.0
  flutter_web3: ^2.1.9
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/metamask_logo.png
  - assets/images/coinbase_logo.png
  - assets/images/trustwallet_logo.png
  - assets/images/other_wallets_icon.png
  - assets/images/logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700



flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#1a1a1a"
    theme_color: "#9353D3"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#1a1a1a"
  adaptive_icon_foreground: "assets/images/logo.png"
